### ISSUE TITLE
file issues

### ISSUE THREAD

**Issue by disruptivepatternmaterial** [bostaunieux/unifi-protect-video-downloader#7]
I pulled your most recent version (and then put in my mqtt path fix, which I need to give you a better PR...) and now I am getting this

[2021-04-09T13:56:56.602Z] DownloadError: Failed downloading motion event
    at processEvent (/app/dist/video_downloader.js:41:19)
    at SequentialTaskQueue.next (/app/node_modules/sequential-task-queue/dist/lib/sequential-task-queue.js:181:45)
    at Immediate.<anonymous> (/app/node_modules/sequential-task-queue/dist/lib/sequential-task-queue.js:64:44)
    at processImmediate (internal/timers.js:461:21) {
  event: {
    camera: '0000000000000000000000000',
    start: 1617976608137,
    end: 1617976615390,
    type: 'smart'
  },
  retries: 5
}

I docker exec'ed in and can CRUD files in /downloads as the user so seems to be ok and this was working. Any ideas on what can be causing this?

docker-compose

version: '2.1'
services:
  unifi-export:
    container_name: unifi-export
    image: 36cae35ca7d5
    restart: always
    network_mode: host
    dns:
      - 192.168.8.125
    environment:
      - UNIFI_HOST=1.1.1.1
      - UNIFI_USER=fish@cat
      - UNIFI_PASS=dog1
      - MQTT_HOST=mqtt://1.1.1.1
      - MQTT_PATH=8PH/unifi
      - TZ=America/New_York
      - CAMERAS=Fish Cam, Dog Cam, Cat Cam
      - DOWNLOAD_PATH=/downloads
    volumes:
      - /mnt/backup/motion:/downloads

**Comment by disruptivepatternmaterial** [comment]
So I rolled back 1.3.0 and it works again, so trying to parse through all your changes since then. Something changed in the file libs it looks like the most.

**Comment by bostaunieux** [comment]
Sorry for not seeing this sooner. Can you test out the latest version and let me know if it's fixed? There was a scoping issue with the queuing mechanism.
